name: go-write-to-file

on:
  schedule:
    - cron: "30 05,13,20 * * *"
  push:
    branches:
          - master


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - run: /bin/sh getdata.sh

    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time

    - name: push to repo
      env:
        TIME: "${{ steps.current-time.outputs.time }}"
      run: |
        git config user.name bhrg3se
        git config user.email bhrg3se@gmail.com
        git add data/*.json
        git commit -m "$TIME: new data pushed"
        git push
